export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_ORG_REQUEST = "REGISTER_ORG_REQUEST";
export const REGISTER_ORG_SUCCESS = "REGISTER_ORG_SUCCESS";
export const REGISTER_ORG_FAIL = "REGISTER_ORG_FAIL";

export const LOAD_ORG_REQUEST = "LOAD_ORG_REQUEST";
export const LOAD_ORG_SUCCESS = "LOAD_ORG_SUCCESS";
export const LOAD_ORG_FAIL = "LOAD_ORG_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ORG_DETAILS_REQUEST = "ORG_DETAILS_REQUEST";
export const ORG_DETAILS_SUCCESS = "ORG_DETAILS_SUCCESS";
export const ORG_DETAILS_FAIL = "ORG_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
